# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/akash/symengine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/akash/symengine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/akash/symengine/CMakeFiles /home/akash/symengine/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/akash/symengine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named symengine

# Build rule for target.
symengine: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 symengine
.PHONY : symengine

# fast build rule for target.
symengine/fast:
	$(MAKE) -f symengine/CMakeFiles/symengine.dir/build.make symengine/CMakeFiles/symengine.dir/build
.PHONY : symengine/fast

#=============================================================================
# Target rules for targets named teuchos

# Build rule for target.
teuchos: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 teuchos
.PHONY : teuchos

# fast build rule for target.
teuchos/fast:
	$(MAKE) -f symengine/utilities/teuchos/CMakeFiles/teuchos.dir/build.make symengine/utilities/teuchos/CMakeFiles/teuchos.dir/build
.PHONY : teuchos/fast

#=============================================================================
# Target rules for targets named catch

# Build rule for target.
catch: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 catch
.PHONY : catch

# fast build rule for target.
catch/fast:
	$(MAKE) -f symengine/utilities/catch/CMakeFiles/catch.dir/build.make symengine/utilities/catch/CMakeFiles/catch.dir/build
.PHONY : catch/fast

#=============================================================================
# Target rules for targets named test_rcp

# Build rule for target.
test_rcp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_rcp
.PHONY : test_rcp

# fast build rule for target.
test_rcp/fast:
	$(MAKE) -f symengine/tests/rcp/CMakeFiles/test_rcp.dir/build.make symengine/tests/rcp/CMakeFiles/test_rcp.dir/build
.PHONY : test_rcp/fast

#=============================================================================
# Target rules for targets named test_arit

# Build rule for target.
test_arit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_arit
.PHONY : test_arit

# fast build rule for target.
test_arit/fast:
	$(MAKE) -f symengine/tests/basic/CMakeFiles/test_arit.dir/build.make symengine/tests/basic/CMakeFiles/test_arit.dir/build
.PHONY : test_arit/fast

#=============================================================================
# Target rules for targets named test_basic

# Build rule for target.
test_basic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_basic
.PHONY : test_basic

# fast build rule for target.
test_basic/fast:
	$(MAKE) -f symengine/tests/basic/CMakeFiles/test_basic.dir/build.make symengine/tests/basic/CMakeFiles/test_basic.dir/build
.PHONY : test_basic/fast

#=============================================================================
# Target rules for targets named test_functions

# Build rule for target.
test_functions: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_functions
.PHONY : test_functions

# fast build rule for target.
test_functions/fast:
	$(MAKE) -f symengine/tests/basic/CMakeFiles/test_functions.dir/build.make symengine/tests/basic/CMakeFiles/test_functions.dir/build
.PHONY : test_functions/fast

#=============================================================================
# Target rules for targets named test_integer

# Build rule for target.
test_integer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_integer
.PHONY : test_integer

# fast build rule for target.
test_integer/fast:
	$(MAKE) -f symengine/tests/basic/CMakeFiles/test_integer.dir/build.make symengine/tests/basic/CMakeFiles/test_integer.dir/build
.PHONY : test_integer/fast

#=============================================================================
# Target rules for targets named test_number

# Build rule for target.
test_number: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_number
.PHONY : test_number

# fast build rule for target.
test_number/fast:
	$(MAKE) -f symengine/tests/basic/CMakeFiles/test_number.dir/build.make symengine/tests/basic/CMakeFiles/test_number.dir/build
.PHONY : test_number/fast

#=============================================================================
# Target rules for targets named test_poly

# Build rule for target.
test_poly: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_poly
.PHONY : test_poly

# fast build rule for target.
test_poly/fast:
	$(MAKE) -f symengine/tests/basic/CMakeFiles/test_poly.dir/build.make symengine/tests/basic/CMakeFiles/test_poly.dir/build
.PHONY : test_poly/fast

#=============================================================================
# Target rules for targets named test_polynomial

# Build rule for target.
test_polynomial: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_polynomial
.PHONY : test_polynomial

# fast build rule for target.
test_polynomial/fast:
	$(MAKE) -f symengine/tests/basic/CMakeFiles/test_polynomial.dir/build.make symengine/tests/basic/CMakeFiles/test_polynomial.dir/build
.PHONY : test_polynomial/fast

#=============================================================================
# Target rules for targets named test_rational

# Build rule for target.
test_rational: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_rational
.PHONY : test_rational

# fast build rule for target.
test_rational/fast:
	$(MAKE) -f symengine/tests/basic/CMakeFiles/test_rational.dir/build.make symengine/tests/basic/CMakeFiles/test_rational.dir/build
.PHONY : test_rational/fast

#=============================================================================
# Target rules for targets named test_series

# Build rule for target.
test_series: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_series
.PHONY : test_series

# fast build rule for target.
test_series/fast:
	$(MAKE) -f symengine/tests/basic/CMakeFiles/test_series.dir/build.make symengine/tests/basic/CMakeFiles/test_series.dir/build
.PHONY : test_series/fast

#=============================================================================
# Target rules for targets named test_series_expansion

# Build rule for target.
test_series_expansion: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_series_expansion
.PHONY : test_series_expansion

# fast build rule for target.
test_series_expansion/fast:
	$(MAKE) -f symengine/tests/basic/CMakeFiles/test_series_expansion.dir/build.make symengine/tests/basic/CMakeFiles/test_series_expansion.dir/build
.PHONY : test_series_expansion/fast

#=============================================================================
# Target rules for targets named test_subs

# Build rule for target.
test_subs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_subs
.PHONY : test_subs

# fast build rule for target.
test_subs/fast:
	$(MAKE) -f symengine/tests/basic/CMakeFiles/test_subs.dir/build.make symengine/tests/basic/CMakeFiles/test_subs.dir/build
.PHONY : test_subs/fast

#=============================================================================
# Target rules for targets named test_diophantine

# Build rule for target.
test_diophantine: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_diophantine
.PHONY : test_diophantine

# fast build rule for target.
test_diophantine/fast:
	$(MAKE) -f symengine/tests/ntheory/CMakeFiles/test_diophantine.dir/build.make symengine/tests/ntheory/CMakeFiles/test_diophantine.dir/build
.PHONY : test_diophantine/fast

#=============================================================================
# Target rules for targets named test_ntheory

# Build rule for target.
test_ntheory: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_ntheory
.PHONY : test_ntheory

# fast build rule for target.
test_ntheory/fast:
	$(MAKE) -f symengine/tests/ntheory/CMakeFiles/test_ntheory.dir/build.make symengine/tests/ntheory/CMakeFiles/test_ntheory.dir/build
.PHONY : test_ntheory/fast

#=============================================================================
# Target rules for targets named test_matrix

# Build rule for target.
test_matrix: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_matrix
.PHONY : test_matrix

# fast build rule for target.
test_matrix/fast:
	$(MAKE) -f symengine/tests/matrix/CMakeFiles/test_matrix.dir/build.make symengine/tests/matrix/CMakeFiles/test_matrix.dir/build
.PHONY : test_matrix/fast

#=============================================================================
# Target rules for targets named test_printing

# Build rule for target.
test_printing: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_printing
.PHONY : test_printing

# fast build rule for target.
test_printing/fast:
	$(MAKE) -f symengine/tests/printing/CMakeFiles/test_printing.dir/build.make symengine/tests/printing/CMakeFiles/test_printing.dir/build
.PHONY : test_printing/fast

#=============================================================================
# Target rules for targets named test_eval_double

# Build rule for target.
test_eval_double: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_eval_double
.PHONY : test_eval_double

# fast build rule for target.
test_eval_double/fast:
	$(MAKE) -f symengine/tests/eval/CMakeFiles/test_eval_double.dir/build.make symengine/tests/eval/CMakeFiles/test_eval_double.dir/build
.PHONY : test_eval_double/fast

#=============================================================================
# Target rules for targets named test_lambda_double

# Build rule for target.
test_lambda_double: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_lambda_double
.PHONY : test_lambda_double

# fast build rule for target.
test_lambda_double/fast:
	$(MAKE) -f symengine/tests/eval/CMakeFiles/test_lambda_double.dir/build.make symengine/tests/eval/CMakeFiles/test_lambda_double.dir/build
.PHONY : test_lambda_double/fast

#=============================================================================
# Target rules for targets named test_cwrapper

# Build rule for target.
test_cwrapper: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_cwrapper
.PHONY : test_cwrapper

# fast build rule for target.
test_cwrapper/fast:
	$(MAKE) -f symengine/tests/cwrapper/CMakeFiles/test_cwrapper.dir/build.make symengine/tests/cwrapper/CMakeFiles/test_cwrapper.dir/build
.PHONY : test_cwrapper/fast

#=============================================================================
# Target rules for targets named test_expression

# Build rule for target.
test_expression: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_expression
.PHONY : test_expression

# fast build rule for target.
test_expression/fast:
	$(MAKE) -f symengine/tests/expression/CMakeFiles/test_expression.dir/build.make symengine/tests/expression/CMakeFiles/test_expression.dir/build
.PHONY : test_expression/fast

#=============================================================================
# Target rules for targets named add1

# Build rule for target.
add1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 add1
.PHONY : add1

# fast build rule for target.
add1/fast:
	$(MAKE) -f benchmarks/CMakeFiles/add1.dir/build.make benchmarks/CMakeFiles/add1.dir/build
.PHONY : add1/fast

#=============================================================================
# Target rules for targets named eval_double1

# Build rule for target.
eval_double1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 eval_double1
.PHONY : eval_double1

# fast build rule for target.
eval_double1/fast:
	$(MAKE) -f benchmarks/CMakeFiles/eval_double1.dir/build.make benchmarks/CMakeFiles/eval_double1.dir/build
.PHONY : eval_double1/fast

#=============================================================================
# Target rules for targets named expand1

# Build rule for target.
expand1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 expand1
.PHONY : expand1

# fast build rule for target.
expand1/fast:
	$(MAKE) -f benchmarks/CMakeFiles/expand1.dir/build.make benchmarks/CMakeFiles/expand1.dir/build
.PHONY : expand1/fast

#=============================================================================
# Target rules for targets named expand2

# Build rule for target.
expand2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 expand2
.PHONY : expand2

# fast build rule for target.
expand2/fast:
	$(MAKE) -f benchmarks/CMakeFiles/expand2.dir/build.make benchmarks/CMakeFiles/expand2.dir/build
.PHONY : expand2/fast

#=============================================================================
# Target rules for targets named expand2b

# Build rule for target.
expand2b: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 expand2b
.PHONY : expand2b

# fast build rule for target.
expand2b/fast:
	$(MAKE) -f benchmarks/CMakeFiles/expand2b.dir/build.make benchmarks/CMakeFiles/expand2b.dir/build
.PHONY : expand2b/fast

#=============================================================================
# Target rules for targets named expand3

# Build rule for target.
expand3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 expand3
.PHONY : expand3

# fast build rule for target.
expand3/fast:
	$(MAKE) -f benchmarks/CMakeFiles/expand3.dir/build.make benchmarks/CMakeFiles/expand3.dir/build
.PHONY : expand3/fast

#=============================================================================
# Target rules for targets named expand6

# Build rule for target.
expand6: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 expand6
.PHONY : expand6

# fast build rule for target.
expand6/fast:
	$(MAKE) -f benchmarks/CMakeFiles/expand6.dir/build.make benchmarks/CMakeFiles/expand6.dir/build
.PHONY : expand6/fast

#=============================================================================
# Target rules for targets named expand7

# Build rule for target.
expand7: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 expand7
.PHONY : expand7

# fast build rule for target.
expand7/fast:
	$(MAKE) -f benchmarks/CMakeFiles/expand7.dir/build.make benchmarks/CMakeFiles/expand7.dir/build
.PHONY : expand7/fast

#=============================================================================
# Target rules for targets named lwbench

# Build rule for target.
lwbench: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lwbench
.PHONY : lwbench

# fast build rule for target.
lwbench/fast:
	$(MAKE) -f benchmarks/CMakeFiles/lwbench.dir/build.make benchmarks/CMakeFiles/lwbench.dir/build
.PHONY : lwbench/fast

#=============================================================================
# Target rules for targets named matrix_add1

# Build rule for target.
matrix_add1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 matrix_add1
.PHONY : matrix_add1

# fast build rule for target.
matrix_add1/fast:
	$(MAKE) -f benchmarks/CMakeFiles/matrix_add1.dir/build.make benchmarks/CMakeFiles/matrix_add1.dir/build
.PHONY : matrix_add1/fast

#=============================================================================
# Target rules for targets named matrix_add2

# Build rule for target.
matrix_add2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 matrix_add2
.PHONY : matrix_add2

# fast build rule for target.
matrix_add2/fast:
	$(MAKE) -f benchmarks/CMakeFiles/matrix_add2.dir/build.make benchmarks/CMakeFiles/matrix_add2.dir/build
.PHONY : matrix_add2/fast

#=============================================================================
# Target rules for targets named matrix_mul1

# Build rule for target.
matrix_mul1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 matrix_mul1
.PHONY : matrix_mul1

# fast build rule for target.
matrix_mul1/fast:
	$(MAKE) -f benchmarks/CMakeFiles/matrix_mul1.dir/build.make benchmarks/CMakeFiles/matrix_mul1.dir/build
.PHONY : matrix_mul1/fast

#=============================================================================
# Target rules for targets named matrix_mul2

# Build rule for target.
matrix_mul2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 matrix_mul2
.PHONY : matrix_mul2

# fast build rule for target.
matrix_mul2/fast:
	$(MAKE) -f benchmarks/CMakeFiles/matrix_mul2.dir/build.make benchmarks/CMakeFiles/matrix_mul2.dir/build
.PHONY : matrix_mul2/fast

#=============================================================================
# Target rules for targets named series

# Build rule for target.
series: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 series
.PHONY : series

# fast build rule for target.
series/fast:
	$(MAKE) -f benchmarks/CMakeFiles/series.dir/build.make benchmarks/CMakeFiles/series.dir/build
.PHONY : series/fast

#=============================================================================
# Target rules for targets named series_expansion_sincos

# Build rule for target.
series_expansion_sincos: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 series_expansion_sincos
.PHONY : series_expansion_sincos

# fast build rule for target.
series_expansion_sincos/fast:
	$(MAKE) -f benchmarks/CMakeFiles/series_expansion_sincos.dir/build.make benchmarks/CMakeFiles/series_expansion_sincos.dir/build
.PHONY : series_expansion_sincos/fast

#=============================================================================
# Target rules for targets named symbench

# Build rule for target.
symbench: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 symbench
.PHONY : symbench

# fast build rule for target.
symbench/fast:
	$(MAKE) -f benchmarks/CMakeFiles/symbench.dir/build.make benchmarks/CMakeFiles/symbench.dir/build
.PHONY : symbench/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... symengine"
	@echo "... teuchos"
	@echo "... catch"
	@echo "... test_rcp"
	@echo "... test_arit"
	@echo "... test_basic"
	@echo "... test_functions"
	@echo "... test_integer"
	@echo "... test_number"
	@echo "... test_poly"
	@echo "... test_polynomial"
	@echo "... test_rational"
	@echo "... test_series"
	@echo "... test_series_expansion"
	@echo "... test_subs"
	@echo "... test_diophantine"
	@echo "... test_ntheory"
	@echo "... test_matrix"
	@echo "... test_printing"
	@echo "... test_eval_double"
	@echo "... test_lambda_double"
	@echo "... test_cwrapper"
	@echo "... test_expression"
	@echo "... add1"
	@echo "... eval_double1"
	@echo "... expand1"
	@echo "... expand2"
	@echo "... expand2b"
	@echo "... expand3"
	@echo "... expand6"
	@echo "... expand7"
	@echo "... lwbench"
	@echo "... matrix_add1"
	@echo "... matrix_add2"
	@echo "... matrix_mul1"
	@echo "... matrix_mul2"
	@echo "... series"
	@echo "... series_expansion_sincos"
	@echo "... symbench"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

