var searchData=
[
  ['x_5f_2165',['x_',['../classSymEngine_1_1Derivative.html#a67f2c6782989da34088ec245bbf84c3d',1,'SymEngine::Derivative']]],
  ['xalloc_2166',['xalloc',['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::istream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::wostringstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::istrstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::basic_ostream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::wiostream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::ofstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::basic_istringstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::basic_ifstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::istringstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::strstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::ostrstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::wfstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::basic_iostream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::wofstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::wstringstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::wistringstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::ifstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::basic_stringstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::basic_istream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::wifstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::ostream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::stringstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::wistream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::ios_base::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::iostream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::basic_fstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::ostringstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::basic_ios::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::basic_ostringstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::wostream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::fstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::basic_ofstream::xalloc()']]],
  ['xor_2167',['Xor',['../classSymEngine_1_1Xor.html',1,'SymEngine']]],
  ['xreplace_2168',['xreplace',['../namespaceSymEngine.html#abf5f5d7f025f8dc0a87fe3f912a94a22',1,'SymEngine']]],
  ['xreplacevisitor_2169',['XReplaceVisitor',['../classSymEngine_1_1XReplaceVisitor.html',1,'SymEngine']]],
  ['xsgetn_2170',['xsgetn',['http://en.cppreference.com/w/cpp/io/basic_streambuf/sgetn.html',1,'std::wstringbuf::xsgetn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sgetn.html',1,'std::streambuf::xsgetn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sgetn.html',1,'std::filebuf::xsgetn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sgetn.html',1,'std::basic_streambuf::xsgetn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sgetn.html',1,'std::basic_stringbuf::xsgetn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sgetn.html',1,'std::strstreambuf::xsgetn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sgetn.html',1,'std::wstreambuf::xsgetn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sgetn.html',1,'std::wfilebuf::xsgetn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sgetn.html',1,'std::stringbuf::xsgetn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sgetn.html',1,'std::basic_filebuf::xsgetn(T... args)']]],
  ['xsputn_2171',['xsputn',['http://en.cppreference.com/w/cpp/io/basic_streambuf/sputn.html',1,'std::basic_filebuf::xsputn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sputn.html',1,'std::wstringbuf::xsputn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sputn.html',1,'std::stringbuf::xsputn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sputn.html',1,'std::wfilebuf::xsputn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sputn.html',1,'std::wstreambuf::xsputn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sputn.html',1,'std::strstreambuf::xsputn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sputn.html',1,'std::basic_stringbuf::xsputn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sputn.html',1,'std::basic_streambuf::xsputn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sputn.html',1,'std::filebuf::xsputn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sputn.html',1,'std::streambuf::xsputn()']]]
];
