/* Generated by re2c 2.0.3 on Thu Apr  8 21:43:39 2021 */
#line 1 "tokenizer.re"
#include "tokenizer.h"
#include "parser.tab.hh"

namespace SymEngine
{

void Tokenizer::set_string(const std::string &str)
{
    // The input string must be NULL terminated, otherwise the tokenizer will
    // not detect the end of string. After C++11, the std::string is guaranteed
    // to end with \0, but we check this here just in case.
    SYMENGINE_ASSERT(str[str.size()] == '\0');
    cur = (unsigned char *)(&str[0]);
}

int Tokenizer::lex(YYSTYPE &yylval)
{
    for (;;) {
        tok = cur;

#line 24 "tokenizer.cpp"
        {
            unsigned char yych;
            yych = *cur;
            if (yych <= '9') {
                if (yych <= '!') {
                    if (yych <= '\f') {
                        if (yych <= 0x00)
                            goto yy2;
                        if (yych <= 0x08)
                            goto yy4;
                        if (yych <= '\v')
                            goto yy6;
                        goto yy4;
                    } else {
                        if (yych <= '\r')
                            goto yy6;
                        if (yych <= 0x1F)
                            goto yy4;
                        if (yych <= ' ')
                            goto yy6;
                        goto yy9;
                    }
                } else {
                    if (yych <= ')') {
                        if (yych == '&')
                            goto yy10;
                        if (yych <= '\'')
                            goto yy4;
                        goto yy10;
                    } else {
                        if (yych <= '-') {
                            if (yych <= '*')
                                goto yy12;
                            goto yy10;
                        } else {
                            if (yych <= '.')
                                goto yy13;
                            if (yych <= '/')
                                goto yy10;
                            goto yy14;
                        }
                    }
                }
            } else {
                if (yych <= '^') {
                    if (yych <= '>') {
                        if (yych <= ';')
                            goto yy4;
                        if (yych <= '<')
                            goto yy17;
                        if (yych <= '=')
                            goto yy18;
                        goto yy19;
                    } else {
                        if (yych <= '@') {
                            if (yych <= '?')
                                goto yy4;
                            goto yy20;
                        } else {
                            if (yych <= 'Z')
                                goto yy22;
                            if (yych <= ']')
                                goto yy4;
                            goto yy10;
                        }
                    }
                } else {
                    if (yych <= '{') {
                        if (yych == '`')
                            goto yy4;
                        if (yych <= 'z')
                            goto yy22;
                        goto yy4;
                    } else {
                        if (yych <= '}') {
                            if (yych <= '|')
                                goto yy10;
                            goto yy4;
                        } else {
                            if (yych <= '~')
                                goto yy10;
                            if (yych <= 0x7F)
                                goto yy4;
                            goto yy22;
                        }
                    }
                }
            }
        yy2:
            ++cur;
#line 42 "tokenizer.re"
            {
                return yytokentype::END_OF_FILE;
            }
#line 95 "tokenizer.cpp"
        yy4:
            ++cur;
        yy5 :
#line 41 "tokenizer.re"
        {
            throw SymEngine::ParseError("Unknown token: '" + token() + "'");
        }
#line 101 "tokenizer.cpp"
        yy6:
            yych = *++cur;
            if (yych <= '\f') {
                if (yych <= 0x08)
                    goto yy8;
                if (yych <= '\v')
                    goto yy6;
            } else {
                if (yych <= '\r')
                    goto yy6;
                if (yych == ' ')
                    goto yy6;
            }
        yy8 :
#line 43 "tokenizer.re"
        {
            continue;
        }
#line 114 "tokenizer.cpp"
        yy9:
            yych = *++cur;
            if (yych == '=')
                goto yy25;
            goto yy5;
        yy10:
            ++cur;
        yy11 :
#line 46 "tokenizer.re"
        {
            return tok[0];
        }
#line 124 "tokenizer.cpp"
        yy12:
            yych = *++cur;
            if (yych == '*')
                goto yy20;
            goto yy11;
        yy13:
            yych = *++cur;
            if (yych <= '/')
                goto yy5;
            if (yych <= '9')
                goto yy27;
            goto yy5;
        yy14:
            yych = *++cur;
            if (yych <= 'Z') {
                if (yych <= '9') {
                    if (yych == '.')
                        goto yy29;
                    if (yych >= '0')
                        goto yy14;
                } else {
                    if (yych <= '@')
                        goto yy16;
                    if (yych == 'E')
                        goto yy33;
                    goto yy30;
                }
            } else {
                if (yych <= 'd') {
                    if (yych == '_')
                        goto yy30;
                    if (yych >= 'a')
                        goto yy30;
                } else {
                    if (yych <= 'e')
                        goto yy33;
                    if (yych <= 'z')
                        goto yy30;
                    if (yych >= 0x80)
                        goto yy30;
                }
            }
        yy16 :
#line 53 "tokenizer.re"
        {
            yylval.string = token();
            return yytokentype::NUMERIC;
        }
#line 158 "tokenizer.cpp"
        yy17:
            yych = *++cur;
            if (yych == '=')
                goto yy34;
            goto yy11;
        yy18:
            yych = *++cur;
            if (yych == '=')
                goto yy36;
            goto yy5;
        yy19:
            yych = *++cur;
            if (yych == '=')
                goto yy38;
            goto yy11;
        yy20:
            ++cur;
#line 47 "tokenizer.re"
            {
                return yytokentype::POW;
            }
#line 175 "tokenizer.cpp"
        yy22:
            yych = *++cur;
            if (yych <= '^') {
                if (yych <= '9') {
                    if (yych >= '0')
                        goto yy22;
                } else {
                    if (yych <= '@')
                        goto yy24;
                    if (yych <= 'Z')
                        goto yy22;
                }
            } else {
                if (yych <= '`') {
                    if (yych <= '_')
                        goto yy22;
                } else {
                    if (yych <= 'z')
                        goto yy22;
                    if (yych >= 0x80)
                        goto yy22;
                }
            }
        yy24 :
#line 52 "tokenizer.re"
        {
            yylval.string = token();
            return yytokentype::IDENTIFIER;
        }
#line 196 "tokenizer.cpp"
        yy25:
            ++cur;
#line 50 "tokenizer.re"
            {
                return yytokentype::NE;
            }
#line 201 "tokenizer.cpp"
        yy27:
            yych = *++cur;
        yy28:
            if (yych <= '^') {
                if (yych <= '@') {
                    if (yych <= '/')
                        goto yy16;
                    if (yych <= '9')
                        goto yy27;
                    goto yy16;
                } else {
                    if (yych == 'E')
                        goto yy33;
                    if (yych <= 'Z')
                        goto yy30;
                    goto yy16;
                }
            } else {
                if (yych <= 'd') {
                    if (yych == '`')
                        goto yy16;
                    goto yy30;
                } else {
                    if (yych <= 'e')
                        goto yy33;
                    if (yych <= 'z')
                        goto yy30;
                    if (yych <= 0x7F)
                        goto yy16;
                    goto yy30;
                }
            }
        yy29:
            yych = *++cur;
            if (yych == 'E')
                goto yy30;
            if (yych != 'e')
                goto yy28;
        yy30:
            yych = *++cur;
        yy31:
            if (yych <= '^') {
                if (yych <= '9') {
                    if (yych >= '0')
                        goto yy30;
                } else {
                    if (yych <= '@')
                        goto yy32;
                    if (yych <= 'Z')
                        goto yy30;
                }
            } else {
                if (yych <= '`') {
                    if (yych <= '_')
                        goto yy30;
                } else {
                    if (yych <= 'z')
                        goto yy30;
                    if (yych >= 0x80)
                        goto yy30;
                }
            }
        yy32 :
#line 54 "tokenizer.re"
        {
            yylval.string = token();
            return yytokentype::IMPLICIT_MUL;
        }
#line 251 "tokenizer.cpp"
        yy33:
            yych = *(mar = ++cur);
            if (yych <= ',') {
                if (yych == '+')
                    goto yy40;
                goto yy31;
            } else {
                if (yych <= '-')
                    goto yy40;
                if (yych <= '/')
                    goto yy31;
                if (yych <= '9')
                    goto yy42;
                goto yy31;
            }
        yy34:
            ++cur;
#line 48 "tokenizer.re"
            {
                return yytokentype::LE;
            }
#line 267 "tokenizer.cpp"
        yy36:
            ++cur;
#line 51 "tokenizer.re"
            {
                return yytokentype::EQ;
            }
#line 272 "tokenizer.cpp"
        yy38:
            ++cur;
#line 49 "tokenizer.re"
            {
                return yytokentype::GE;
            }
#line 277 "tokenizer.cpp"
        yy40:
            yych = *++cur;
            if (yych <= '/')
                goto yy41;
            if (yych <= '9')
                goto yy42;
        yy41:
            cur = mar;
            goto yy32;
        yy42:
            yych = *++cur;
            if (yych <= '^') {
                if (yych <= '9') {
                    if (yych <= '/')
                        goto yy16;
                    goto yy42;
                } else {
                    if (yych <= '@')
                        goto yy16;
                    if (yych <= 'Z')
                        goto yy30;
                    goto yy16;
                }
            } else {
                if (yych <= '`') {
                    if (yych <= '_')
                        goto yy30;
                    goto yy16;
                } else {
                    if (yych <= 'z')
                        goto yy30;
                    if (yych <= 0x7F)
                        goto yy16;
                    goto yy30;
                }
            }
        }
#line 55 "tokenizer.re"
    }
}

} // namespace SymEngine
