find_path(PTHREAD_INCLUDE_DIR pthread.h)
find_library(PTHREAD_LIBRARY pthread)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(PTHREAD DEFAULT_MSG PTHREAD_INCLUDE_DIR PTHREAD_LIBRARY)
